### ISSUE TITLE
Feedly can't read the RSS of subverses.

### ISSUE THREAD

**Issue by ghost** [voat/voat#725] opened 2015-08-16 03:09 UTC
The RSS of the subverses are not working with feedly.com.
It could be a problem with feedly.com or Voat.co
The RSS of the page(https://voat.co/rss) is working fine.

The same happens in feedreader.com.

**Comment by DanielFlamino** [comment] 2015-08-16 03:49
Potential duplicate of #659

**Comment by leofidus** [comment] 2015-08-16 19:40
I made some [unofficial RSS feeds](https://voat.co/v/whatever/comments/410336) as a workaround.

**Comment by PuttItOut** [comment] 2016-11-03 21:29
Closed as code has changed significantly since issue logged.

**Closed by PuttItOut** 2016-11-03 21:29 UTC
