### ISSUE TITLE
SCP and CCP should remain after submission/comment deletion

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#727] opened 2015-08-16 18:44 UTC
There have been spammers that delete their downvoted comments and submissions in order to get back up the threshold limits and essentially "reenable" their accounts. A good solution for this is to make that SCP and CCP permanently affect the account.

**Comment by voat** [comment] 2015-08-16 19:17
Duplicate of #138 :)

**Closed by voat** 2015-08-16 19:17 UTC

**Comment by DanielFlamino** [comment] 2015-08-16 19:39
I thought that was just to make it not calculate on the fly, and not to make it stay after deletion. My bad, I guess.

**Comment by voat** [comment] 2015-08-16 20:29
You're right, the purpose was not the same but the implementation will tackle both issues. The code should now be ready: https://github.com/voat/voat/commit/7ef473dc93e5e2c74a825854db17c6aee2cbb991.

**Comment by DanielFlamino** [comment] 2015-08-16 21:11
Good to know that! :)
