### ISSUE TITLE
Korean text not showing up in submission title

### ISSUE THREAD

**Issue by revi** [voat/voat#664] opened 2015-07-16 04:40 UTC
See [this /v/test post](https://voat.co/v/test/comments/288851) and it should generate "테스트" in the ()s. It doesn't.

**Comment by jksg** [comment] 2015-07-16 05:59
Dupe of #411. Higher Unicode characters are being stripped for security / convenience until a better solution can be implemented.

**Closed** 2015-07-16 09:46 UTC
Labels: duplicate
