### ISSUE TITLE
User friendly subverse customization tool

### ISSUE THREAD

**Issue by voat** [voat/voat#325] opened 2015-02-22 15:31 UTC
Our existing way of allowing subverse owners to customize the looks of their subs is all well and good, but it opens the doors to abuse. I propose the following:
- sub owners should be able to customize subs without having to know anything about CSS
- all custom assets should be uploaded to and hosted on voat servers
- only specific CSS elements should be customizable

**Comment by talons1337** [comment] 2015-02-25 13:29
There are my thoughts on this: 

1. Having user-friendly customization built into Voat is a good idea. People will be able to quickly make their subs be, well, theirs. Nothing bland. I don't see how this can go wrong, so I think it should be implemented. 

2. Hosting custom assets on Voat servers sounds fine and I don't think it should be too much of a problem, and it's good for security. However, there are some questions that should be addressed. Namely: 

  * What file types are supported: Subverse customisation goes beyond just images. It may be necessary to, for example, host font files (.ttf, .woff, etc.). 
  * What file sizes are supported: Rather than upload lots of images and make many HTTP requests each time a page loads, it's better to upload images as just one image. The problem is, these images can get pretty big. There are other reasons too, for example, CSS3 animations do not support changing the background-image property. To animate images, users need to use background-position instead.
  * Users should be able to upload stylesheets as well, and then `@import` them into their CSS document. This is mostly for fonts or frameworks like bootstrap. 

3. This is quite vague, perhaps the wrong terms are used in the description, and it's still easy to abuse, since pretty much every CSS property has a legitimate use, and usually it's not a niche one (or else the W3C wouldn't have added it to the spec). I really don't see how abuse can be fixed, besides having CSS rights given out by special users who are good with CSS or something like that. 

  * Limiting what elements can be selected simply lessens what users are able to do with CSS, without affecting abuse in the slightest.
  * Limiting what CSS properties can be modified also lessens what users can do, especially since the properties that are abused are extremely useful ones, and quite necessary in big themes. The properties that I believe were used in the abuse that prompted this issue to be added are `z-index`, `height`, `width`, and `position:absolute;`. Every single one of these properties is important, *especially* `height` and `width`. 
  * The "CSS empowering" idea would work like this: All users who have displayed proficiency in styling a subverse (*cough @Nurdoidz cough*) are given a badge that allows them to grant CSS modification powers to any other user, but that user cannot grant those powers to other users. If enough empowered users grant CSS powers to a user who already has CSS powers (which will be shown on their profile as a special score only visible to CSS users), that user gets promoted to empowered level as well. The empowering would not be limited to only "empowering", if a user, after getting CSS rights, is found to be abusive, their rights can be stripped by enough "de-empowering".

**Comment by d3dave** [comment] 2015-03-23 08:17
I want to add that currently styling strictly via CSS is severely limiting. I have no ability to change the text of the `Hot` link in the tabmenu. I propose adding an ability to change some specific text resources in a subverse. This might seem like too much, but if, for example, one is moderating a sub about refrigerators and they don't like the `Hot` text and want to change it to `Cold`, they currently can't do that.

**Comment by talons1337** [comment] 2015-03-23 12:57
It is possible. I have a lot of assignments to do but once they are done I'm resuming my CSS tutorials. 

(psst! Use `:after`)

**Comment by DanielFlamino** [comment] 2015-03-23 19:50
[Doesn't :after only add the content afterwards, instead of replacing it?](https://developer.mozilla.org/en-US/docs/Web/CSS/::after)

**Comment by talons1337** [comment] 2015-03-23 20:56
Using stylesheets, make the font size of the original box 0, then set it to whatever you want in the `:after` block. I'd provide examples but I'm on my phone

**Comment by PuttItOut** [comment] 2016-11-03 21:30
Closed as this is not a planned feature.

**Closed by PuttItOut** 2016-11-03 21:30 UTC
Labels: feature request, help wanted
