### ISSUE TITLE
Context link highlights sibling comments

### ISSUE THREAD

**Issue by mgiuffrida** [voat/voat#655] opened 2015-07-14 06:41 UTC
Example: https://voat.co/v/LifeProTips/comments/206805/610674/611275#611275

This is the context link for the 2nd comment, "And Twilight for Android". However, the sibling comment, "Also redshift..." is also highlighted.

**Comment by fringenerd** [comment] 2015-07-14 08:14
Context links highlight all comments on the same "level". I don't mind it. I think of it as a feature rather than a bug.

**Comment by Nurdoidz** [comment] 2015-07-14 16:26
@fringenerd 

The purpose of the context link is to give context to a specific comment. For example, in @mgiuffrida's situation, the URL is referencing four pieces of information:

~~~
/comments/POST_ID/COMMENT_ID/HIGHLIGHT_COMMENT_ID/ANCHOR
~~~

* `POST_ID`: The ID number of the post.
* `COMMENT_ID`: The ID number of the comment.
* `HIGHLIGHT_COMMENT_ID`: Which comment to highlight.
* `ANCHOR`: Which anchor the browser should jump to.

Since intended behavior is to highlight the specific comment marked with `HIGHLIGHT_COMMENT_ID`, this issue is not intended behavior and can be classified as a bug.

**Comment by quantumwannabe** [comment] 2015-07-14 18:15
This bug only highlights sibling comments after the one whose ID is in the URL.

The reason why is because the variable "highlightClass" is not scoped to the inside of the foreach loop (instead it is scoped to the page as a whole) and so it is not reset between loop iterations. 

See [_SubmissionComment.cshtml Line 273](https://github.com/voat/voat/blob/239a049fbaf278d3841798d412ecb65e8518a253/Voat/Voat.UI/Views/Shared/Submissions/_SubmissionComment.cshtml#L273)

**Comment by fringenerd** [comment] 2015-07-15 02:56
Ah, I've only ever seen it highlight all the comments on a specific level (presumably because it was meant to highlight the first comment), so I just assumed it was meant to work that way.

Okay, bug.

**Comment by PuttItOut** [comment] 2015-07-19 19:04
Fixed in Comment Branch

**Closed by PuttItOut** 2015-07-19 19:04 UTC
