### ISSUE TITLE
Auto-link thingy doesn't ignore code blocks

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#405] opened 2015-04-23 22:06 UTC
As reported on [this post](https://voat.co/v/voatdev/comments/84558) by AgentOrange

How to reproduce:

Make a post/comment with the following markdown

    ~~~
    http://example.com
    ~~~

This will output:

~~~
[http://example.com](http://example.com)
~~~

**Comment by PuttItOut** [comment] 2015-04-24 21:31
Yeah, this is a bigger issue than it seems when factoring in performance. The regex match become extremely complex fast and the alternative of manual processing in C# is unattractive.

Once I get the API done I'll revisit this issue as all server side expandos need to be aware if they are in a code block or not.

**Comment by talons1337** [comment] 2015-05-08 07:15
The auto-link thingy also breaks when you put a subname (eg /v/voat) into a link ``(eg. [http://voat.co/](This is a link on /v/voat, linking to the main page)`` outputs ``This is a link on [/v/Voat](/v/Voat), linking to the main page``.

**Comment by MagicalBlob** [comment] 2016-10-07 13:19
Duplicate of #787

**Closed by MagicalBlob** 2016-10-07 13:19 UTC
