### ISSUE TITLE
Can't upload avatar

### ISSUE THREAD

**Issue by lmontrieux** [voat/voat#419] opened 2015-05-22 00:59 UTC
It seems that I can't upload an avatar or voat. The image (attached) is a 68kb, 500x344 jpeg.
Instead of the uploaded avatar appearing, the default one is replaced by... nothing. It's just empty.

I'm using Firefox 38.0.1 on Mac OS X.

![1984](https://cloud.githubusercontent.com/assets/203099/7762034/272adf6a-0069-11e5-8dff-c40ce63ec5cb.jpg)

**Comment by talons1337** [comment] 2015-05-22 14:50
Try resizing it to see if it works.

**Comment by voat** [comment] 2015-05-23 09:26
There is something special with this image that makes the thumb generation method go nuts. When I re-saved it in gimp as jpg, I could use it just fine. I'll try to find out what is causing this and at least throw out an error message.

**Comment by voat** [comment] 2015-05-23 09:33
I found the cause: this image has an indexed pixel format. I'll see what can be done about these.

**Comment by voat** [comment] 2015-05-23 11:32
Fixed with next patch by updating .net image library.

**Closed by voat** 2015-05-23 11:32 UTC
Labels: bug
