### ISSUE TITLE
Own reply shows up twice after expanding siblings.

### ISSUE THREAD

**Issue by RobertWarrenGilmore** [voat/voat#680] opened 2015-07-23 23:56 UTC
procedure:
1. Find a comment whose children are partially collapsed. ("Load more replies")
2. Reply to the comment.
3. Expand the children of the comment from the first step by clicking "Load more replies".

expected result:
More comments will be loaded, with no duplicates.

actual result:
More comments are loaded, including a duplicate of our own reply from the second step.

**Comment by jksg** [comment] 2015-07-24 07:54
Related or dupe of #621

**Comment by PuttItOut** [comment] 2015-08-01 02:07
This is because the comment is appended to the dom on submittal but then retrieved from updated cache upon load more. Closed because duplicate bug entry.

**Closed by PuttItOut** 2015-08-01 02:07 UTC
Labels: bug, duplicate
