### ISSUE TITLE
Can't submit in Russian?

### ISSUE THREAD

**Issue by aosheter** [voat/voat#722] opened 2015-08-13 13:54 UTC
How to produce the bug:

1. Go to /v/Russia
2. Make a post title in Russian (mine was "Кто еще беженец Редита?")
3. Hit submit.

Error message: Sorry, submission title may not be less than 5 characters.

4. Hit submit again after 60 seconds.

Error message: Well this is embarrassing. Something went wrong and let's face it, nobody's happy about it. We'll dispatch our monstersquad to take a look at it right away!

**Comment by Luk3M** [comment] 2015-08-14 20:54
Duplicate of #411  
The reason, by @jksg and @DanielFlamino : 
>all characters above ANSI number 255 are stripped, leaving only basic Latin and some accented characters.

>It was a temporary decision until a proper filter was created IIRC.

**Closed** 2016-09-16 08:01 UTC
Labels: wontfix
